version: '3.8'

services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile.dev
    ports:
      - '4040:5173'
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      backend:
        condition: service_healthy

  backend:
    build:
      context: backend
      dockerfile: Dockerfile.dev
    ports:
      - '5050:5000'
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - PORT=5000
      - DATABASE_URL=postgresql://aamella:pw@postgres:5432/esnmarket
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:5000/v1']
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  postgres:
    image: postgres
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: aamella
      POSTGRES_PASSWORD: pw
      POSTGRES_DB: esnmarket
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $POSTGRES_USER']
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

volumes:
  postgres_data:
