# syntax=docker/dockerfile:1

ARG NODE_VERSION=20.12.2
FROM node:${NODE_VERSION}-alpine

RUN npm install -g pnpm
RUN apk add --no-cache openssl

WORKDIR /usr/src/app

# Copy package files first
COPY package.json pnpm-lock.yaml ./

# Install dependencies
RUN pnpm install

# Copy the rest of the source files
COPY . .

# Generate Prisma Client
RUN pnpx prisma generate

# Expose the port
EXPOSE 5000

# Run the application
CMD pnpm start:dev
